os: linux
dist: xenial
language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - nightly
  - pypy3
env: TOXENV=py,coveralls

jobs:
  include:
    - python: "3.8"
      env: TOXENV=stylecheck,docs-html
    - python: "2.7"
      env: TOXENV=py27,coveralls
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

notifications:
  email: false
